group 'com.imin.printer.imin_printer'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            allowInsecureProtocol = true
            url 'https://www.jitpack.io'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.2'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            allowInsecureProtocol = true
            url 'https://www.jitpack.io'
        }
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'com.imin.printer.imin_printer'

    compileSdk flutter.compileSdkVersion

    defaultConfig {
        minSdk flutter.minSdkVersion
        targetSdk flutter.compileSdkVersion
        multiDexEnabled true
        consumerProguardFiles "consumer-rules.pro"
    }

    compileOptions {
        // AGP 8.x + Flutter mới -> Java 17
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError false
    }
}

dependencies {
    // Imin SDK
    implementation files('libs/iminPrinterSDK-15_V1.3.2_2505261539.jar')
    implementation files('libs/IminStraElectronicSDK_V1.2.jar')

    // Rx
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'

    // AndroidX
    implementation "androidx.multidex:multidex:2.0.1"

    // Imin official lib
    implementation 'com.github.iminsoftware:IminPrinterLibrary:V1.0.0.15'

    // Glide
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'

    // Test
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:5.18.0'
}
